### ISSUE TITLE
seem the size of the template file is limited ?

### ISSUE THREAD

**Issue by icoco** [pyrocms/lex#17]

**Comment by RyanThompson** [comment]
Shouldn't be - check your memory / fpm configuration perhaps?

**Comment by icoco** [comment]
thanks for reply,  seem it should not be memory issue, the template file only about 600 lines, then while I use lex generate target file, it not works fine as normal, I have to split the file to two file, one is 300 lines another is 300 lines, then everything is fine , I am confuse with this case...

**Comment by RyanThompson** [comment]
@obrignoni do you have any input on this?

Sounds like a recursion issue or something. I honestly do not know.

**Comment by icoco** [comment]
yes... I face the issue, then I split the 'big' file as two files, then render it one by one, then conjunct two as single file.

**Comment by icoco** [comment]
I can send to u if you want see the file via other way, thanks.
