### ISSUE TITLE
How to access variables from out loop?

### ISSUE THREAD

**Issue by LuanMaik** [pyrocms/lex#18]
How can I access variables from out loop inside loop?

**Example:**

```
$projects = [
            ['name'=> 'Project1']
];

$date = '2017-06-21';
```

```
{{ projects }}
    <h3>{{ name }}</h3> <small>{{date}}</small>
{{ /projects }}
```

**Comment by RyanThompson** [comment]
Even though this is 2.x let's keep it in the main pyrocms/pyrocms repository issues.

That said.. 2.x has been deprecated for a long time I am not sure what kind of support exists for this. And knowing Lex you may not be able to reach variables outside of the scope of the loop :-/ It's a procedural parser so there is an order and limitation to it's parsed data.

**Comment by LuanMaik** [comment]
Are there others libs like this with extra powers?

**Comment by LuanMaik** [comment]
I found this one https://github.com/tomasbonco/comper-template-parser seems more powerfull

**Comment by RyanThompson** [comment]
IMO - Twig would be the best you can get.

**Comment by LuanMaik** [comment]
It's exactly what i need, thanks @RyanThompson
