### ISSUE TITLE
Hyphens in Variable Names

### ISSUE THREAD

**Issue by mtudor** [pyrocms/lex#6]
Just wondering if there's any reason why a hyphen is not allowed in a variable name?  The parser just ignores a variable with a hyphen because the RegEx doesn't catch it.

I've implemented a change locally which allows hyphenated variables but was wondering if this was a deliberate choice (i.e. am I letting myself in for a whole world of pain ;-))?

**Comment by dhrrgn** [comment]
I will not be allowing this.  Please see here for more on why: https://github.com/pyrocms/pyrocms/pull/1922
